# Spring
context:
    initializer:
        classes: de.novatec.graphqlclient.BeansInitializer

# Application
graphql-client:
    server-url: https://demo.getmesh.io/api/v2/demo/graphql
    profit-margin: 10
logging:
    level:
        de.novatec: DEBUG
