name: Build & Test

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build
      run: ./gradlew assemble
    - name: Unit Test
      run: ./gradlew test
    - name: Integration Test
      run: ./gradlew integrationTest
    - name: Acceptance Test
      if: github.event == 'push'
      run: ./gradlew acceptanceTest
